### ISSUE TITLE
Push Delivery is so slow 100 Push Takes 45 Seconds

### ISSUE THREAD

**Issue by judgetr** [spacialdb/gcm#20]
Hello, i have tested for several times and it all takes around 40 seconds just for 100 push notification.

I'm able to send 150.000 push notification in under 60 second in ios so i dont think thats acceptable for 100 notification to deliver in 40 seconds.

my code

start time 2015-05-05 19:15:36 +0300

pusher=GCM.new(application.google_api_key)

2.1.2 :010 >  for i in 0..100
2.1.2 :011?>      puts i
2.1.2 :012?>      options={data: {message:"#{i}. iteration",title:"test"}}
2.1.2 :013?>      register_id=["device-token"]
2.1.2 :014?>      pusher.send(register_id,options)
2.1.2 :015?>      end

i noticed that it only go to the next payload when the previos one is already sent.is that the problem?

**Comment by kashif** [comment]
dear @judgetr yes so with your loop you are sending the pushes sequentially one after another in a synchronous manner to a single device, so that is the reason why it is "slow"... 

It is not really a problem since typically you never send one message after another to a device... to send a message to a few devices with the same message is possible by sending an array of device tokens...

If you want to spam ...uhh I mean message a device repeatedly you can perhaps use some asynchronous library for ruby... and then it I am not sure what will happen at the google end...

hope that helps!

**Comment by kaneda** [comment]
Seconding what @kashif said, there are a variety of options for dealing with this, none of which would mean a change for GCM.

1) Do these in bulk, instead of one at a time
2) Set up a delayed job or queue in Ruby (see Sidekiq + Redis, great combo!)
3) Read the expectations around GCM delivery (within 24 hours, as possible, no guarantee of speedy delivery)

**Comment by evrenios** [comment]
hello @kashif and @kaneda

1)i entered a single device token id to test i'm not spaming or anything.
2)Beside i noticed the slow delivery when sending notifications to everyone.
3)I'm already using sidekiq worker system.

do you have any time result for sending notifications? For example how much times does it takes to deliver 100 notification to 100 user?

**Comment by kashif** [comment]
dear @evrenios have a look at this paper: http://www.cse.buffalo.edu/~demirbas/publications/gcm.pdf for some insights...
